### ISSUE TITLE
lua invalid key to 'next'

### ISSUE THREAD

**Issue by Syronin** [Srlion/sfs#4]
I use this library in netstream instead of pon. Installing the latest version gave an error.

 1. next - [C]:-1
 2. encoder - gamemodes/tpmode/gamemode/lib/sfs.lua:244
 3. encoder - gamemodes/tpmode/gamemode/lib/sfs.lua:233
 4. encode - gamemodes/tpmode/gamemode/lib/sfs.lua:149
 5. Start - gamemodes/tpmode/gamemode/lib/netstream.lua:69
 6. v - gamemodes/tpmode/gamemode/lib/nw.lua:20
 7. unknown - lua/includes/modules/hook.lua:96

**Comment by Srlion** [comment]
Thank you!

**Comment by Syronin** [comment]
So I still get an error. I decided to print the information that is used in encode

[1]:
                [1]:
                                ["Draw"]        =       true
                [2222]:
                                ["DoorFraction"]        =       Антейку
                ["cache"]:
                ["name"]        =       SrawlNManager
                
[ERROR] invalid key to 'next'
  1. next - [C]:-1
   2. encoder - gamemodes/tpmode/gamemode/lib/sfs.lua:244
    3. encoder - gamemodes/tpmode/gamemode/lib/sfs.lua:233
     4. encode - gamemodes/tpmode/gamemode/lib/sfs.lua:149
      5. Start - gamemodes/tpmode/gamemode/lib/netstream.lua:71
       6. v - gamemodes/tpmode/gamemode/lib/nw.lua:21
        7. unknown - lua/includes/modules/hook.lua:96
        
By removing the empty table under the cache key. The error has disappeared.

**Comment by Srlion** [comment]
Ok try this fix
