### ISSUE TITLE
Color encoding problems

### ISSUE THREAD

**Issue by TankNut** [Srlion/sfs#6]
Using version 3.0.3, trying to encode colors under certain circumstances (especially involving Vector():ToColor()) throws an error as colors don't round or truncate any of their channels internally, causing https://github.com/Srlion/sfs/blob/master/sfs.lua#L194 to return nil trying to index something like `chars[254.00001525879]`

```
lua_run sfs.encode(Vector(1, 0.84, 0.3):ToColor())
> sfs.encode(Vector(1, 0.84, 0.3):ToColor())...
[ERROR] gamemodes/eternity/gamemode/lib/sh_sfs.lua:402: invalid value (nil) at index 3 in table for 'concat'
1. table_concat - [C]:-1
2. encode - gamemodes/eternity/gamemode/lib/sh_sfs.lua:402
3. unknown - lua_run:1
```

**Comment by Srlion** [comment]
Thank you for the report!

**Comment by Srlion** [comment]
I'm not sure if I should round to nearest integer, floor, or ceil, what do you think?

**Comment by TankNut** [comment]
I'd say go with math.Round, that's going to be the most intuitive for people

**Comment by Srlion** [comment]
I will go with math.floor as it actually gets rounded down no matter what you give it.

**Comment by Srlion** [comment]
Thank you again for your contributions <3
